name: Echo Bot

on:
  workflow_dispatch:

jobs:
  run-echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install
        run: pip install telethon
      - name: Run
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
        run: python echo_bot.pyp